### ISSUE TITLE
Move to using VSSDK meta package

### ISSUE THREAD

**Issue by mrlacey** [mrlacey/Rapid-XAML-Toolkit#126]
see 

https://github.com/madskristensen/Madskristensen.VisualStudio.SDK

https://blogs.msdn.microsoft.com/visualstudio/2018/10/10/simplify-extension-development-with-packagereference-and-the-vssdk-meta-package/

**Comment by crutkas** [comment]
is this something wts should do as well?

**Comment by mrlacey** [comment]
meta package doesn't include the following which are needed.

- Microsoft.VisualStudio.LanguageServices
- Microsoft.VisualStudio.Telemetry
- Microsoft.VisualStudio.TextManager.Interop.12.0

**Comment by mrlacey** [comment]
The SDK meta package works for adding the VS references but the change to using PackageReferences breaks other behavior. Specifically, this is the inclusion of NuGet provided DLLs packaged inside the VSIX.
Other projects have also hit this issue but still no clear workaround. X-Ref https://gitter.im/Microsoft/extendvs?at=5c36863354d8bb07ccc5a233

**Comment by mrlacey** [comment]
The workaround in https://github.com/NuGet/Home/issues/5899 seems to unblock this

**Comment by mrlacey** [comment]
Want to test on a nightly build before closing.

**Comment by mrlacey** [comment]
Verified 0.1.19011.1
on 16.0.0 p1.1
