### ISSUE TITLE
Create VS marketplace entry

### ISSUE THREAD

**Issue by mrlacey** [mrlacey/Rapid-XAML-Toolkit#13]
Need to create the entry in https://marketplace.visualstudio.com/

Also, need to create assets and copy to accompany the listing.

X-Ref #12

**Comment by crutkas** [comment]
i may need to do this one.  I know we can set up a group account.

**Comment by mrlacey** [comment]
@crutkas I was expecting you might have to do this, depending on what account it's published under.

Issue was created so this wasn't forgotten about and left until the last minute and done in a rush

**Comment by crutkas** [comment]
I think you can create the text / body and i can whip up the physical entry on marketplace

**Comment by mrlacey** [comment]
Necessary details at https://github.com/microsoft/Rapid-XAML-Toolkit/blob/dev/Assets/Marketplace/entry.md
