### ISSUE TITLE
Fix CI & Nightly builds on AzurePipelines

### ISSUE THREAD

**Issue by mrlacey** [mrlacey/Rapid-XAML-Toolkit#223]
Now requiring VS2019 to build the project.
Azure Pipelines definitions need updating accordingly.

X-Ref #221

**Comment by mrlacey** [comment]
Also, need to bump version number on the nightly build to 0.2.*

**Comment by mrlacey** [comment]
@sibille assigning to you now but not expecting anything until you return from vacation. ;)

**Comment by sibille** [comment]
I'm back from vacation and working on it!

**Comment by mrlacey** [comment]
All building again now. Yay!
