### ISSUE TITLE
Generate XAML based on methods (not just properties)

### ISSUE THREAD

**Issue by mrlacey** [mrlacey/Rapid-XAML-Toolkit#280]
It should be possible to generate XAML based on a method in the [ViewModel] class.

Some frameworks (Prism & Caliburn.Micro--and possibly others) can bind directly to methods in the ViewModel/DataContext. Some other `EventToCommand` behaviors can also do this. `x:Bind` can also be used to bind directly to method calls on the DataContext.
As XAML can be written to connect directly to methods it is desirable to be able to generate such XAML as well.

_This is a follow-on from #259 where this was the original request but that issue became sidetracked with other questions and requests._

---

Early thoughts:
- map `method()` as a special type in mappings. Will map to any parameterless method.
- also support mapping types `method(T)` which maps to any method that takes a single parameter of any type. This takes lower priority than a mapping for a specific type.
- support mapping `method(MyEventArgs)` which maps to any method that takes a single argument of `MyEventArgs`.
- Support up to two parameters. e.g. `method(T, T)`
- only work with methods that return `void` or `Task`.
- only work with public methods.
- add **$method$** as a placeholder that maps to the method name.

Questions for investigation:
- Is it necessary to have placeholders for method parameters?

**Comment by XuJin186** [comment]
Of course.

**Comment by mrlacey** [comment]
Notes on examples of what it needs to be possible to generate

**Method with single parameter**

```cs
public void OnPhotoTaken(CameraControlEventArgs args)
{
    // ...
}
```

```xml
<controls:CameraControl
    x:Name="cameraControl"
    x:Uid="CameraPage_CameraControl"
    cm:Message.Attach="[Event PhotoTaken] = [OnPhotoTaken($eventArgs)]" />
```

**Example Two**

```cs
public void OnItemSelected(SampleOrder clickedItem)
{
    // ...
}
```

```xml
<controls:AdaptiveGridView
            cm:Message.Attach="[Event ItemClick] = [OnItemSelected($clickedItem)]"
```

**Example with no parameters**

```cs
        public void ZoomIn() => _zoomService?.ZoomIn();
```

```xml
<AppBarButton x:Uid="InkDrawPicture_ZoomInButton" Icon="ZoomIn"
     cm:Message.Attach="ZoomIn" BorderBrush="Transparent" BorderThickness="0,0,0,0" />
```

**No parameters - second example**

```cs
public void Undo()
{
    ClearSelection();
    _undoRedoService.Undo();
}
```

```xml
<AppBarButton x:Uid="InkSmartCanvas_UndoButton" Icon="Undo" cm:Message.Attach="Undo" BorderBrush="Transparent" BorderThickness="0,0,0,0" />
```

**parameter that references another element in view**

not sure how possible this will be with generated element names.

```cs
public async void SwitchTheme(ElementTheme theme)
{
    await ThemeSelectorService.SetThemeAsync(theme);
}
```

```xml
<RadioButton
    x:Name="ThemeLightButton"
    x:Uid="Settings_Theme_Light"
    cm:Message.Attach="SwitchTheme(ThemeLightButton.Tag)"
    IsChecked="{x:Bind ViewModel.ElementTheme, Converter={StaticResource EnumToBooleanConverter}, ConverterParameter=Light, Mode=OneWay}"
    FontSize="15"
    GroupName="AppTheme">
    <RadioButton.Tag>
        <xaml:ElementTheme>Light</xaml:ElementTheme>
    </RadioButton.Tag>
</RadioButton>
```

**Caliburn long form example**

```cs
public class ShellViewModel : IShell
{
    public bool CanSayHello(string name)
    {
        return !string.IsNullOrWhiteSpace(name);
    }

    public void SayHello(string name)
    {
        MessageBox.Show(string.Format("Hello {0}!", name));
    }
} 
```

```xml
        <Button Content="Click Me">
            <i:Interaction.Triggers>
                <i:EventTrigger EventName="Click">
                    <cal:ActionMessage MethodName="SayHello">
                        <cal:Parameter Value="{Binding ElementName=Name, Path=Text}" />
                    </cal:ActionMessage>
                </i:EventTrigger>
            </i:Interaction.Triggers>
        </Button>
```

**Comment by mrlacey** [comment]
>> Is it necessary to have placeholders for method parameters?
> Of course.

@xujin950710 Are you saying that given a method like `MyMethod(string id, int amount)`, you'd need to be able to include "id" or "amount" in the generated XAML?

I'm not saying this couldn't be possible I just don't know any frameworks that use these values in this way.

Can you share an example of a method and the XAML you've written to call into it that uses the parameter names?

**Comment by mrlacey** [comment]
No negative feedback - assuming all is good
