### ISSUE TITLE
Getting intermittent RXT999 exceptions when using Xamarin Forms

### ISSUE THREAD

**Issue by petvetbr** [mrlacey/Rapid-XAML-Toolkit#283]
**Describe the bug**
Getting intermittent RXT999 exceptions when using Xamarin Forms

**To Reproduce**
Happens during build with a specific XAML file (attached). When it happens, it seems to go away if I edit the XAML file in some way (ie. remove the <?xml version="1.0" encoding="UTF-8"?> on top of the file and save). Seems like a possible cache issue.

**Expected behavior**
A clear and concise description of what you expected to happen or the output to be.

**Additional context**
Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Error	RXT999	Unexpected error occurred while parsing XAML.	ExTrack	C:\src\ExTrack\ExTrack\ExTrack\Views\TimeSheetsTemplates\TimeSheetsMenuPage.xaml	1		Please log an issue to https://github.com/Microsoft/Rapid-XAML-Toolkit/issues Reason: System.NullReferenceException: Object reference not set to an instance of an object.
   at RapidXamlToolkit.Logging.RxtLogger.RecordError(String message, Boolean force) in C:\Users\matt\Documents\GitHub\mrlacey-RXT\VSIX\RapidXamlToolkit\Logging\RxtLogger.cs:line 26
   at RapidXamlToolkit.Logging.RxtLogger.RecordException(Exception exception) in C:\Users\matt\Documents\GitHub\mrlacey-RXT\VSIX\RapidXamlToolkit\Logging\RxtLogger.cs:line 57
   at RapidXamlToolkit.VisualStudioIntegration.VisualStudioAbstraction.<GetProjectType>g__ReferencesNuGetPackageWithNameContaining|5_2(Project proj, String name, <>c__DisplayClass5_0& ) in C:\Users\matt\Documents\GitHub\mrlacey-RXT\VSIX\RapidXamlToolkit\VisualStudioIntegration\VisualStudioAbstraction.cs:line 83
   at RapidXamlToolkit.VisualStudioIntegration.VisualStudioAbstraction.GetProjectType(Project project) in C:\Users\matt\Documents\GitHub\mrlacey-RXT\VSIX\RapidXamlToolkit\VisualStudioIntegration\VisualStudioAbstraction.cs:line 168
   at RapidXamlToolkit.XamlAnalysis.RapidXamlDocument.Create(ITextSnapshot snapshot, String fileName, IVisualStudioAbstraction vsa) in C:\Users\matt\Documents\GitHub\mrlacey-RXT\VSIX\RapidXamlToolkit\XamlAnalysis\RapidXamlDocument.cs:line 57

**Comment by petvetbr** [comment]
`
    <ContentPage
    x:Class="ExTrack.Views.TimeSheetsTemplates.TimeSheetsMenuPage"
    xmlns="http://xamarin.com/schemas/2014/forms"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:components="clr-namespace:ExTrack.Components;assembly=ExTrack"
    xmlns:converters="clr-namespace:XamarinUniversity.Converters;assembly=XamU.Infrastructure"
    xmlns:d="http://xamarin.com/schemas/2014/forms/design"
    xmlns:infrastructure="clr-namespace:XamarinUniversity.Infrastructure;assembly=XamU.Infrastructure"
    xmlns:ios="clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    ios:Page.UseSafeArea="true"
    mc:Ignorable="d">
    <ContentPage.Content>
        <Grid BackgroundColor="White" RowSpacing="0">
            <Grid.RowDefinitions>
                <RowDefinition Height="auto" />
                <RowDefinition Height="50" />
                <RowDefinition Height="*" />
                <RowDefinition Height="Auto" />
            </Grid.RowDefinitions>
            <components:HeaderView />
            <Grid Grid.Row="1" BackgroundColor="{StaticResource Orange}">
                <Label
                    Margin="10,5"
                    FontSize="Large"
                    HorizontalTextAlignment="Start"
                    Text="TIMESHEETS"
                    TextColor="White"
                    VerticalTextAlignment="Center" />
            </Grid>
            <ListView
                Grid.Row="2"
                BackgroundColor="{StaticResource BackgroundGray}"
                HasUnevenRows="True"
                ItemsSource="{Binding MenuList}"
                SelectedItem="{Binding SelectedMenu, Mode=TwoWay}">
                <ListView.Behaviors>
                    <infrastructure:EventToCommandBehavior Command="{Binding SelectedCommand}" EventName="ItemTapped" />
                </ListView.Behaviors>
                <ListView.ItemTemplate>
                    <DataTemplate>
                        <ViewCell>
                            <Grid>
                                <Label
                                    Margin="20,10,0,5"
                                    FontAttributes="Bold"
                                    FontSize="Large"
                                    Text="{Binding Description}" />
                                <BoxView
                                    BackgroundColor="Gray"
                                    HeightRequest="2"
                                    VerticalOptions="End" />
                            </Grid>
                        </ViewCell>
                    </DataTemplate>
                </ListView.ItemTemplate>
            </ListView>

            <components:ToolbarView
                Grid.Row="3"
                CurrentIndex="3"
                IsEnabled="{Binding IsBusy, Converter={converters:NotBooleanConverter}}" />
        </Grid>
    </ContentPage.Content>
</ContentPage>`

**Comment by petvetbr** [comment]
[TimeSheetsMenuPage.zip](https://github.com/microsoft/Rapid-XAML-Toolkit/files/3688669/TimeSheetsMenuPage.zip)

**Comment by mrlacey** [comment]
@petvetbr Thanks for reporting this.

Based on the information available (thanks for all the detail) it looks like an issue querying the project system. That it reports as RXT999 this indicates a problem reporting a problem which makes it very hard to diagnose.

I've just uploaded version 0.3.10 to the marketplace and this includes improved error handling and reporting in the area where I think the problem lies. If you se the issue go away with this new version then good, if not, we should get some more useful details in the error logs.

If a problem still remains can you please also provide details of
- which version of Visual Studio you are using
- what your solution structure looks like. (i.e. what platform heads you have projects for, whether you're using a shared project or standard library for shared content, and any other projects you have in the solution.

Thanks.

**Comment by mrlacey** [comment]
I'm going to close this on the assumption that the changes in the 0.3.10 release did address the problem.
Please comment below if they didn't and we can reopen this issue.
