### ISSUE TITLE
Visual Studio for Mac Extension

### ISSUE THREAD

**Issue by prabh-62** [mrlacey/Rapid-XAML-Toolkit#290]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I see there is an [extension published](https://marketplace.visualstudio.com/items?itemName=MattLaceyLtd.RapidXamlPreview) for `Visual Studio for Windows`. In the future, would there be a extension for `Visual Studio for Mac` ?

**Describe alternatives you've considered**

**Additional context**

**Comment by mrlacey** [comment]
Hi @prabh-62 
Support for Visual Studio for Mac is something that I'd definitely like to have but shipping a V1 for Windows is a priority first.

**Comment by mrlacey** [comment]
Never gonna happen :(
https://devblogs.microsoft.com/visualstudio/visual-studio-for-mac-retirement-announcement/
