### ISSUE TITLE
UWP not connecting to SQLExpress Northwind db

### ISSUE THREAD

**Issue by msavazzi** [mrlacey/Rapid-XAML-Toolkit#302]
**Describe the bug**
I get an error on connection to the SQLEXPRESS DB. I've tried even the troubleshooting (tcp/ip active etc..)

**To Reproduce**
compile example and run

**Expected behavior**
to connect. 

**Additional context**
even tried the 127.0.0.1 as suggested in the posts.
Tried to disable firewall

**Comment by mrlacey** [comment]
@msavazzi I think you've logged this issue in the wrong place. There's nothing in the Rapid XAML Toolkit about connecting to a database.
