### ISSUE TITLE
VS2019 ask to Update from 0.8.3 to 0.9.0, but fails each time

### ISSUE THREAD

**Issue by MagicAndre1981** [mrlacey/Rapid-XAML-Toolkit#341]
VS2019 shows me daily that an update is available from 0.8.3 to 0.9.0

![vs2019_090_update](https://user-images.githubusercontent.com/8274816/79849792-3f2d0d80-83c3-11ea-9195-20e917568024.png)

, but this fails because I always get message that latest version of the extension is already installed:

![vs2019_090_update1](https://user-images.githubusercontent.com/8274816/79850173-d1351600-83c3-11ea-90bd-c39bedacc682.png)

I still see a reference to version [0.8.3 in this file](https://github.com/mrlacey/Rapid-XAML-Toolkit/blob/124050bb722b29f43af014136b9b7a12621dd7e6/VSIX/RapidXaml.Shared/Properties/AssemblyInfo.cs#L37), maybe this causes the error.

**Comment by mrlacey** [comment]
I've seen this with other projects too. 
It appears to be an issue with how Visual Studio handles the extension update process. I have escalated to Microsoft.

**Comment by MagicAndre1981** [comment]
ok, can you change this version to 0.9.1 for all files and release this as a test? I've uninstalled the extension and downloaded a fresh 0.9 VSIX and installed it but again the same update shows up.

**Comment by mrlacey** [comment]
I think this happens when you've already installed the other extensions this tries to include.
Try uninstalling "Rapid XAML Templates", restart VS, and then the update should work.

**Comment by MagicAndre1981** [comment]
no, I've completely uninstall all rapid extensions, downloaded the newest vsix from marketplace, installed it and VS shows the 0.9.0 update again.

// Edit: I see other extensions have newer versions. Try to keep the versions in sync for all extensions and release a new test update, may it fixes it.

**Comment by MagicAndre1981** [comment]
I've just tested it on a VS2019 where the extension was never installed before. Here I also get the 0.9.0 update offered. So I configured VS to use Open VSIX Gallery inside VS2019, installed the nightly update and now everything is fine. 

If I get it on a fresh system, you should also see this.

**Comment by mrlacey** [comment]
Version 0.9.3 is now in the marketplace and should hopefully address this

**Comment by MagicAndre1981** [comment]
I got 0.9.225 from Open VSIX Gallery, normal market place entry in VS2019 showed no update.

I manually removed again all RapidXAML extensions and installed last VSIX from market place (which is much smaller compared to older version).

now the 0.9.225 shows up again on Open VSIX Gallery.

![rapid_openvsix](https://user-images.githubusercontent.com/8274816/80341213-4f7d3680-8862-11ea-8f91-30fe927c0015.png)

![image](https://user-images.githubusercontent.com/8274816/80346937-dd115400-886b-11ea-891a-2a75c156bcc1.png)


does 225 mean patch to 0.9.2 and is intended to be lower compared to 0.9.3?

I removed Open VSIX Gallery now as extension feed source from inside VS2019 to ignore this update.

**Comment by mrlacey** [comment]
225 is bigger than 3 and so is treated as a newer version.

It looks like you installed 0.9.3 from the marketplace but VS is detecting a newer version from the vsix gallery.

The Gallery versions should always match or be newer than what's in the marketplace.

It also look like the gallery entries aren't all be versioned as expected so I've raised a separate issue to track that. (#343)

**Comment by mrlacey** [comment]
Hopefully being on version 0.10.* means this is no longer an issue.
Closing this to tidy up but feel free to reopen if still happening.
Follow up for versioning the vsix gallery versions will be tracked on #343

**Comment by MagicAndre1981** [comment]
yes, I no longer have this with 0.10.* . I already subscribed to #343 and watch it
