### ISSUE TITLE
Extend custom analysis options

### ISSUE THREAD

**Issue by mrlacey** [mrlacey/Rapid-XAML-Toolkit#364]
There are lots of scenarios where having custom analysis limited to specific named elements is limiting. Custom Analysis should be extended to make it easier to work with multiple element types.

**THIS HAS LOTS OF POTENTIAL TO HAVE A BIG PERFORMANCE IMPLICATION - BE CAREFUL**

Scenarios where this might be useful:

* Wanting to ensure that `Mode` is specified with `Binding` markup
* Checking use of "any" markup extension
* Combine analysis logic for multiple similar types

Possible options:

* Support `TargetType = "ANY"` (or equivalent)
* Support TargetType = {multiple defined values}
* Support TargetType = "ANY" but with a filter (where filter uses a `Contains` match for a substring of the whole element string)
* Support matching by attribute name and adding an attribute specific analyzer
* Add a markupextension-specific analyzer

Nice to have but not considered the details - A built-in analyzer to warn about possible side-effects (perf issues) from configured values

**Comment by sonnemaf** [comment]
I would love to have this. Especially for a warning on the missing Mode property on a Binding. It should support the MarkupExtensions syntax.

![image](https://user-images.githubusercontent.com/9335559/86453915-d2b57f80-bd1e-11ea-8f7b-c8e67dc3dc6e.png)

**Comment by mrlacey** [comment]
This will also enable #355

**Comment by mrlacey** [comment]
Looking good for inclusion in 0.11

![image](https://user-images.githubusercontent.com/189547/92380997-f96aaa80-f101-11ea-9b9f-fad71f92c256.png)

Requires different approaches to get the two different ways of setting bindings though.

```cs

public class Issue364ExampleAnalyzer : ICustomAnalyzer
{
    public string TargetType() => "ANYCONTAINING:=\"{Binding";

    public AnalysisActions Analyze(RapidXamlElement element, ExtraAnalysisDetails extraDetails)
    {
        var result = AnalysisActions.EmptyList;

        foreach (var attribute in element.Attributes)
        {
            if (attribute.HasStringValue)
            {
                var attrValue = attribute.StringValue;

                if (attrValue.StartsWith("{Binding ") && !attrValue.Contains(" Mode="))
                {
                    result.HighlightAttributeWithoutAction(RapidXamlErrorType.Warning, "ISSUE364", $"Set binding mode for '{attribute.Name}'.", attribute);
                }
            }
        }

        return result;
    }
}

public class Issue364ExampleAnalyzer2 : ICustomAnalyzer
{
    public string TargetType() => "Binding";

    public AnalysisActions Analyze(RapidXamlElement element, ExtraAnalysisDetails extraDetails)
    {
        var result = AnalysisActions.EmptyList;

        if (!element.Attributes.Any(a => a.Name == "Mode"))
        {
            result.HighlightWithoutAction(RapidXamlErrorType.Warning, "ISSUE364", $"Set binding mode.");
        }

        return result;
    }
}
```

**Comment by sonnemaf** [comment]
@mrlacey this is great. You are a genius. Looking forward for a public release.

**Comment by mrlacey** [comment]
closing as ready to include in 0.11 - hopefully later this week
