### ISSUE TITLE
Vs2019 16.6.3 is freezing When "Compare with Previous" on Xaml

### ISSUE THREAD

**Issue by EmilAlipiev** [mrlacey/Rapid-XAML-Toolkit#366]
**Describe the bug**
If i make changes on xaml and select "Compare with Previous", Vs2019 is freezing completely and i have to kill from the task manager. it wasnt the case for earlier updates but started on this version. I disabled the extensions now and everything is normal. I only tested on a Xamarin.Forms project.

**To Reproduce**

1. Change a xaml file and save
2. Go to team explorer
3. Right Click on that xaml file and choose Compare with Previous
4. It freezes the solution

**Comment by mrlacey** [comment]
This doesn't just happen with the "Compare with Previous" option. It appears to happen when any (one or more) .xaml files are opened in the diff view.
My investigations continue....

**Comment by mrlacey** [comment]
@EmilAlipiev I've just submitted version 0.10.1 to the marketplace and that includes a fix for this issue.

Thank you so much for taking the time to report this issue. Please let me know if you have any further problems, questions, or suggestions.
