### ISSUE TITLE
 Rapid Xaml Extension makes Xamarin.Forms Xaml changes saving very slow

### ISSUE THREAD

**Issue by EmilAlipiev** [mrlacey/Rapid-XAML-Toolkit#372]
Using Roslyn Analyzers, every time I save a xaml change, it take 10+ seconds. I believe it is caused together with Hotreload on Android. I have tested only on Android emulator using hotreload.
Once I disable the extension everything is normal.
 
VS 2019 16.6.4

**Comment by mrlacey** [comment]
The [Rapid Xaml RoslynAnalyzers](https://marketplace.visualstudio.com/items?itemName=MattLaceyLtd.RapidXamlRoslynAnalyzers) package should have no impact when saving files.
[Rapid XAML Analysis](https://marketplace.visualstudio.com/items?itemName=MattLaceyLtd.RapidXamlAnalysis) does do some work when a file is saved.
Is it only slow when also debugging / using HotReload or is it also noticeably slow when not debugging?
Is this in a project you can share to help me recreate what you are seeing?

**Comment by EmilAlipiev** [comment]
My bad sorry it wasn't Roslyn Analyzers but Rapid Xaml extension. I have enabled disabled each extension one by one and Rapid Xaml is causing 2 problems 
1- when i delete an empty line, it delay like 2 secs
2- Saving xaml changes 3+ secs without debugging. While debugging with hotreload much longer and VS Ide is freezing for a few seconds.
 
I thought it was Roslyn Analyzers because when I checked Help->VS performance manager menu. it was showing this line. but this seems to be only once happened as written.

![image](https://user-images.githubusercontent.com/10422347/87603453-50eb2c00-c6f8-11ea-9b66-f32e84556127.png)

**Comment by mrlacey** [comment]
There are lots of potential causes of this and I also know there are lots of opportunities for performance improvements that could be causing this.

To further help me get a fix out faster:
- Is this in a particularly large project?
- Does the solution contain multiple other projects beyond the ones for the Xamarin.Forms app(s)?
- Is this in all documents? or just some?

In the meantime, I'll look at possible temporary workarounds.

**Comment by EmilAlipiev** [comment]
I have just tested with 2 different projects. 1 is a new project and another one is quite large project. yes it only occurs on large project.
It has only XF project as typical solution structure .net standard, android, ios and uwp. 
in all documents of large project but in small project even xaml is complicated it doesnt occur. So it looks like that it depends on the size of the project but not the size of the xaml.

**Comment by EmilAlipiev** [comment]
Actually let me ask what exactly does Rapid Xaml? i couldnt find a detailed documentation. is there anything written available?

**Comment by EmilAlipiev** [comment]
Just fixing my statement above after testing better :) It occurs on large project with large xaml file. Here how you can reproduce it. 
- clone this repo https://github.com/xamarin/Xamarin.Forms
- open in VS and change something in this xaml  Xamarin.Forms\Xamarin.Forms.Controls.Issues\Xamarin.Forms.Controls.Issues.Shared\A11yTabIndex.xaml
- delete an empty line first and see there is a delay
- try to save this change now, you can see that mouse pointer is turning into loader for 2-3 secs. larger the xaml, time increases seems like

**Comment by mrlacey** [comment]
> Just fixing my statement above after testing better :) It occurs on large project with large xaml file. Here how you can reproduce it.
> 
> * clone this repo https://github.com/xamarin/Xamarin.Forms
> * open in VS and change something in this xaml  Xamarin.Forms\Xamarin.Forms.Controls.Issues\Xamarin.Forms.Controls.Issues.Shared\A11yTabIndex.xaml
> * delete an empty line first and see there is a delay
> * try to save this change now, you can see that mouse pointer is turning into loader for 2-3 secs. larger the xaml, time increases seems like

Thanks for this. It will definitely help me get a solution out faster.

**Comment by mrlacey** [comment]
There's definitely a perf issue that is affecting more than just the scenario mentioned above.

Version 0.10.3 is now available from the marketplace.
Included in this version is an option to disable automatic analysis every time a file is saved.

![image](https://user-images.githubusercontent.com/189547/87959456-d3823b80-caaa-11ea-9e1b-1673d2dc8877.png)

Additionally, there is now monitoring how long analysis takes. If it takes a longer time than expected, a warning suggesting that automatic analysis on file save be disabled.

![image](https://user-images.githubusercontent.com/189547/87960513-4e982180-caac-11ea-9cd0-1cd21e30af7e.png)

Further work on performance monitoring and improvement will continue.

**Comment by EmilAlipiev** [comment]
I have bunch of   warnings like below in the output of Rapid-Xaml toolkit. Do you know what is this to do? is it related?


```
Could not load file or assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=' or one of its dependencies. The system cannot find the file specified.
Fusion Log:
WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

```

**Comment by EmilAlipiev** [comment]
It was followed by this warning

```
to look for CustomAnalyzers."
[23:54:28.258]  System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at RapidXamlToolkit.XamlAnalysis.RapidXamlDocument.GetCustomAnalyzers(String folderToSearch)
[23:54:28.258]  mscorlib
[23:54:28.258]  Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
[23:54:28.258]     at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at RapidXamlToolkit.XamlAnalysis.RapidXamlDocument.GetCustomAnalyzers(String folderToSearch)
[23:54:28.258]  Could not load file or assembly 'Xamarin.Forms.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
Fusion Log:
WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
```

**Comment by mrlacey** [comment]
@EmilAlipiev those errors are related to Custom Analysis support.
If you're not creating your own XAML analyzers you definitely want this turned off as it will impact performance.

Tools > Options > Rapid XAML > Analysis : Enable Custom Analysis = False

**Comment by mrlacey** [comment]
Future performance improvements will come in time but closing this for now.
Please reopen or raise new issues for specific examples of things running slowly
