### ISSUE TITLE
False Warning RXT401 if "IsChecked" comes before "Checked" or "Unchecked"

### ISSUE THREAD

**Issue by HeinzKessler** [mrlacey/Rapid-XAML-Toolkit#448]
Using Version 0.11.0:
If both Ckecked and Unckecked event handlers are present, but they appear after the IsChecked Property, then a false RXT401 is generated,
Example:

```
<CheckBox
    Name="FormattedTextCheckbox"
    Margin="5,2"
    HorizontalAlignment="Left"
    VerticalContentAlignment="Center"
    IsChecked="{Binding ElementName=TextBlockSettingUserControl, Path=IsBodyTextFormatted}"
    Checked="FormattedTextCheckbox_Checked"
    Unchecked="FormattedTextCheckbox_Unchecked">
    Enable text formatting
</CheckBox>
```

If the Checked and Unchecked attributes come before IsChecked, the bug disappears. 

Expected: RXT401 behavior not related to the order of the attributes

**Comment by mrlacey** [comment]
This functionality has been released as part of [v 0.12.0 and is available now](https://marketplace.visualstudio.com/items?itemName=MattLaceyLtd.RapidXamlToolkit).
