### ISSUE TITLE
Icons of the editor-extra are almost not visible in dark theme

### ISSUE THREAD

**Issue by LokiMidgard** [mrlacey/Rapid-XAML-Toolkit#462]
**Describe the bug**
Icons are almost not visible in dark mode.
**To Reproduce**
1. Set Visual Studio to dark mode.
2. Add Xaml that shows an icon using editor-extra

**Expected behavior**
The Icon should be a color that is visible

**Additional context**

![image](https://user-images.githubusercontent.com/389101/108625979-13990a80-744e-11eb-87cb-22fb643226a5.png)

**Comment by mrlacey** [comment]
Adding this capability.
I thought this was already handled :( sorry.

![image](https://user-images.githubusercontent.com/189547/112728429-2b692000-8f1f-11eb-86ad-3e17ffb5ef20.png)
