### ISSUE TITLE
Visual Studio 2019 Editor locks up with "please wait for an editor command to finish" after update and installation of the latest VS 2019 build.

### ISSUE THREAD

**Issue by tmosson1** [mrlacey/Rapid-XAML-Toolkit#495]
So I was receiving a "please wait for an editor command to finish" issue when I tried to edit code.  It was related to the latest update of the Rapid XAML Toolkit conflicting with the update to the latest Visual Studio 2019 build because when I disabled the Rapid XAML Toolkit I was able to use the editor. 

Steps to reproduce:

1.  Update the Rapid XAML Toolkit to latest release.
2.  Update to the latest Visual Studio 2019 build (Version 16.11.1).

**Comment by mrlacey** [comment]
Try just disabling the "Editor Extras" extension. I think I've narrowed the issue down to there.

**Comment by mrlacey** [comment]
solution is incoming

**Comment by mrlacey** [comment]
I've installed [Editor Extensions v0.13.1](https://marketplace.visualstudio.com/items?itemName=MattLaceyLtd.RapidXamlEditorExtras) and can confirm the issue is now fixed.
