### ISSUE TITLE
WPF tag on package causes confusion

### ISSUE THREAD

**Issue by michael-hawker** [mrlacey/Rapid-XAML-Toolkit#498]
See https://developercommunity.visualstudio.com/t/wpf-project-type-filter-doesnt-show-wpf-projects/1561875

By default there's a `Desktop` tag for representing WPF project type. Rapid XAML adds a `WPF` tag, so that seems great to select in the list, but then WPF projects don't show up...

**Comment by mrlacey** [comment]
Fixed in v 0.13.1.1 of the Rapid XAML Templates package. :/
