### ISSUE TITLE
Custom XAML Analysis is not working for Microsoft Visual Studio Professional 2019 Version 16.11.5

### ISSUE THREAD

**Issue by YakupIpek21** [mrlacey/Rapid-XAML-Toolkit#503]
**Describe the bug**

After having generated the projects with the Custom Analyzer Project-Template I follow the instructions as in **Step 4. Reference the analyzer in your project**, however no warning is displayed.

**To Reproduce**

1. Reference the project containing the analyzer in a wpf project with a xaml page or window.

**Expected behavior**

Warning to be displayed in Visual Studio.

**Note**
RapidXaml.BuildAnalysis Nuget generates warnings as expected

**Comment by mrlacey** [comment]
can you share what you've done?

**Comment by YakupIpek21** [comment]
Thank you for the quick response.

1. By using the project template (Custom Rapid Xaml Analyzer) I have created the projects
![image](https://user-images.githubusercontent.com/7056714/153022958-81cb3f4d-4a2e-41e8-9217-34a33c8b886a.png)

2. I have updated the auto-generated cs-file as follows:
public string TargetType() => "AnyOf:TextBlock,TextBox";
(I havent made any changes to the Analyze-Method, hence when the IsEnabled-Attribute is missing for a **TextBlock** or **TextBox** a warning should be displayed)

3. In the same solution I have created a wpf project and referenced the project containing the custom analyzer (I have also tried by creating a nuget package and referencing it)

4. I have added a xaml-page with a TextBlock without an IsEnabled-Attribute, however there is no warning displayed

My Visual Studio 2019 version is: Microsoft Visual Studio Professional 2019 Version 16.11.5

**Comment by mrlacey** [comment]
Two things:

1. Make sure that custom analysis is enabled in the options:
 
![image](https://user-images.githubusercontent.com/189547/153040159-fbd36f7f-d050-4bd3-9067-a2350d0c6325.png)

2. I can recreate the issue when using `ANYOF:Textblock,TextBox`. However things work as expected if I just specify a single element type; e.g. `public string TargetType() => "TextBlock";`


I'll continue looking into why the "ANYOF:" version isn't working as expected.

**Comment by YakupIpek21** [comment]
Single element type works.

Looking forward to the fixed version.

Thank you very much.

**Comment by YakupIpek21** [comment]
Regarding the working scenario with the single type, I'd like to know if it also works when the project containing the custom analyzer is added as a nuget package as it seems to fail in my case. I've enabled custom analysis in the options.

Note: it works when the project is added as a project reference


Update: it works now, I am not sure why it took so long to trigger the custom analysis

**Comment by mrlacey** [comment]
> Regarding the working scenario with the single type, I'd like to know if it also works when the project containing the custom analyzer is added as a nuget package as it seems to fail in my case. I've enabled custom analysis in the options.
> 
> Note: it works when the project is added as a project reference
> 
> Update: it works now, I am not sure why it took so long to trigger the custom analysis

I've found that Visual Studio's caching of referenced assemblies can sometimes be a bit too aggressive and can lead to this problem.
Unfortunately, while testing new custom analyzers, I often find I need to forcibly delete the contents of the `bin` and `obj` directories to get this to work correctly. Sometimes it's even necessary to restart VS. 😞

**Comment by mrlacey** [comment]
> Single element type works.

Yes, the logic for handling the "ANYOF:" prefix wasn't right. 
"ANYCONTAINING" and "AnyOrChildrenContaining:" do work though. Although, I recognize this doesn't help you right now.

**Comment by mrlacey** [comment]
I've just released version 0.13.2 of [the Analysis extension](https://marketplace.visualstudio.com/items?itemName=MattLaceyLtd.RapidXamlAnalysis) to the marketplace and have confirmed that this fixes the issue you were seeing.

I'll now update the BuildAnalysis library too (for #505)

**Comment by YakupIpek21** [comment]
Great, thanks a lot 👍

**Comment by mrlacey** [comment]
If you have any problems, comments, or suggestions please raise another issue.
If you love it, please [leave a rating/review](https://marketplace.visualstudio.com/items?itemName=MattLaceyLtd.RapidXamlToolkit&ssr=false#review-details) or consider [sponsorship](https://github.com/sponsors/mrlacey)  :smile:
