### ISSUE TITLE
AnyOf does not work as expected

### ISSUE THREAD

**Issue by YakupIpek21** [mrlacey/Rapid-XAML-Toolkit#506]
**Describe the bug**
Targeting multiple types as depicted in the picture does not work as expected.
![image](https://user-images.githubusercontent.com/7056714/153579268-9dc24e21-2478-4e10-aff6-04685564bd2e.png)

Warnings are generated for more types, as shown in the following picture:
![image](https://user-images.githubusercontent.com/7056714/153579634-f7940388-f70a-4102-babb-b26776467d31.png)

**To Reproduce**

1. Create a custom analyzer with the **ANYOF** prefix
2. Add the project containing the custom analyzer as a reference to a project which contains the xaml files
3. Add Grid, StackPanel, TextBlock, TextBox tags
4. Save the file in order to trigger the analysis

**Expected behavior**
Only types declared in the TargetType property with the **ANYOF** prefix should be analyzed

**Additional context**
Have installed the latest RapidXaml.Analysis extension (version 0.13.2)

**Comment by mrlacey** [comment]
What are the warnings reported in the Error List?
It looks like the other warnings being reported are the ones that are built into the tool and are automatically applied to all documents.

**Comment by YakupIpek21** [comment]
I've tried to reproduce the above mentioned behaviour, but have failed to do so. It works as expected.

**Comment by mrlacey** [comment]
Feel free to reopen if you find this happening again.
