### ISSUE TITLE
Interest in the build-time analyzers, maybe split out to own repository

### ISSUE THREAD

**Issue by mterwoord** [mrlacey/Rapid-XAML-Toolkit#514]
Hi! 

Awesome project you have. I read about supporting VS2022 would be hard. How hard would it be to get the build-time analyzers working with VS2022 or at least newer roslyn versions and SDK-style projects?

I'd try to help out, if the analyzer stuff was a separate repository. Have you considered splitting the poject up like that?

**Comment by mrlacey** [comment]
Porting to VS2022 is on my plan and I'm hoping to start it soon.
Unfortunately the XAML analyzer functionality is going to be the hardest to port as it uses APIs that are no longer available in VS2022.
Restructuring into multiple repositories is not something I'm considering. It would be a lot of work (based on past experience) for no guaranteed benefit (again based on past experience)--sorry.

**Comment by mrlacey** [comment]
Sorry, I will not be splitting out the build time analysis into a separate repository.
It's a lots easier to manage everything in one repo and the functionality is so tied to the XamAnalysis functionality that's shared with the Editor extension and the AutoFix package that multiple repos would make things harder for me and make progress even slower.
