### ISSUE TITLE
BuildAnalysis fails when parsing xaml files containing CheckBox elements

### ISSUE THREAD

**Issue by hailedev** [mrlacey/Rapid-XAML-Toolkit#515]
**Description**
After installing the nuget package RapidXaml.BuildAnalysis to a WPF application, when it is built RapidXaml.AnalysisExe fails when encountering a xaml file that contains a CheckBox element

**Steps to reproduce**
1. In Visual Studio 2019 create a new project and select the WPF App (.NET Framework) template
2. Add the nuget package RapidXaml.BuildAnalysis and install latest version 0.13.0
3. In MainWindow.xaml add an empty CheckBox to the grid
4. Clean and rebuild the solution

The build fails with error Unexpected error occurred while parsing XAML (v0.13.0.0) (RXT999)
![0](https://user-images.githubusercontent.com/6165355/195480989-80723124-102a-4275-a7ff-4bf8a6b21216.png)

**Expected behavior**
The solution is built successfully

**Comment by mrlacey** [comment]
Hmmmmm. This doesn't happen for .NET Core projects. 😕 
More investigation needed...

**Comment by mrlacey** [comment]
It's fixed in [v0.14.1](https://www.nuget.org/packages/RapidXaml.BuildAnalysis/0.14.1)
