### ISSUE TITLE
The readme says MAUI is supported, but MAUI is not support in VS2019.

### ISSUE THREAD

**Issue by juicebyjustin** [mrlacey/Rapid-XAML-Toolkit#521]
This tool looks like a great companion to the accelerator extension you have. However, I am a bit confused. Your readme says that MAUI is supported. 

I see the extensions' settings include support for MAUI. Opening any MAUI project in VS2019 does not work. The prerequisite to MAUI is Visual Studio 2022 17.3 or greater. MAUI is not supported in VS 2019. 

What is the best way to use this tool with MAUI XAML when VS2019 does not support MAUI?

VS2019 Version 16.11.27

Source: https://learn.microsoft.com/en-us/dotnet/maui/get-started/installation?tabs=vswin

**Comment by juicebyjustin** [comment]
I must be missing something. I saw other tickets say they are able to work with this in VS2022.

**Comment by mrlacey** [comment]
The "toolkit" part is due to this being a suite of tools. 
The main extension doesn't **yet** work with VS2022, but some of the functionality packaged and distributed via NuGet does work with MAUI & VS2022.

_Hopefully_, I'll be able to get this all tidied up ad better documented soon.

**Comment by juicebyjustin** [comment]
Thanks for the response. I must be missing something. Using VS2022 and the default MAUI template, I added NuGet package RapidXaml.CodeGen.Maui (v0.1.0). 

In VS2019 this works in a WPF app. I see where this works in the gif in the readme. I swear I'm not a numb skulll.

VS2022 v17.6.4
dotnet v7
Default VS MAUI Template: .NET MAUI App

Test Solution: https://github.com/juicebyjustin/rapidxaml-maui-test

![image](https://github.com/mrlacey/Rapid-XAML-Toolkit/assets/2144123/6fed2438-572e-46c2-ae5e-8282e3792564)
![image](https://github.com/mrlacey/Rapid-XAML-Toolkit/assets/2144123/3589cfdf-90d7-478f-acb9-a1bd68d15d3a)


![image](https://github.com/mrlacey/Rapid-XAML-Toolkit/assets/2144123/0fcae161-a0fd-44f7-91c2-09a06c4f8adf)

```csharp
    public class Item
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
```

```csharp
    public class ItemsViewModel
    {
        public Models.Item Model { get; set; }
    }
```

**Comment by mrlacey** [comment]
There are multiple NuGet packages and they each do different (very targetted) things.
The XAML generation from ViewModels functionality only works with the Visual Studio extension.
sorry for the confusion

**Comment by juicebyjustin** [comment]
Not a problem at all. Thanks for your responses. I'll patiently await the release for VS2022 support.
