### ISSUE TITLE
Usage of ReSharper

### ISSUE THREAD

**Issue by ArchieCoder** [mrlacey/Rapid-XAML-Toolkit#63]
This is not a bug per se, but more of a general suggestion that using ReSharper is great just format and reduce the code when possible. In the following screenshot, ReSharper points out that it might be an hidden bug with the useless "else". I'm a big fan of ReSharper for more than 10 years :) It saves me at least one real bug per project.

![resharper](https://user-images.githubusercontent.com/1608424/39668140-634f5606-5093-11e8-9dc7-94eb16ceefe5.png)

**Comment by mrlacey** [comment]
@ArchieCoder  wrong screenshot?

**Comment by ArchieCoder** [comment]
@mrlacey Indeed, I fixed the screenshot.

**Comment by mrlacey** [comment]
@ArchieCoder I've been through the R# inspection recommendations and updated the code accordingly. I don't recall anything specific about a "useless else" but if there's something else you think could be improved please let me know.

**Comment by mrlacey** [comment]
regarding the updated screenshot.
Assuming that's from [here](https://github.com/Microsoft/Rapid-XAML-Toolkit/blob/af0dbf0f9b05f81bbcae783dc0f7e9a7d70b0893/RapidXAML.VSIX/RapidXamlToolkit/Analyzers/CSharpAnalyzer.cs#L163)

I'll update accordingly
