### ISSUE TITLE
Invalid binding on int property

### ISSUE THREAD

**Issue by corradocavalli** [mrlacey/Rapid-XAML-Toolkit#65]
**Describe the bug**
ViewModel exposes an int property Age, RapidXaml generates a slider that leads to a runtime error:	Invalid binding path 'ViewModel.Age' : Cannot bind type 'System.Int32' to 'System.Double' without a converter

**To Reproduce**
Added a MyViewModel class directly under project root
   public class MyViewModel:ViewModelBase
    {
        public int Age { get; set; }
        private string userName;    
        public string UserName
        {
            get
            {
                return this.userName;
            }

            set
            {
                if (value != this.userName)
                {
                    this.userName = value;
                    base.RaisePropertyChanged();

                }
            }
        }
    }

right clicked on it and selected UWP, here's generated XAML
<Grid Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
        <Grid>
            <Grid.RowDefinitions>
                <RowDefinition Height="Auto" />
                <RowDefinition Height="Auto" />
                <RowDefinition Height="Auto" />
                <RowDefinition Height="*" />
            </Grid.RowDefinitions>
            <TextBlock Text="Age"
                       Grid.Row="0" />
            <Slider Minimum="0"
                    Maximum="100"
                    x:Name="Age"
                    Value="{x:Bind ViewModel.Age, Mode=TwoWay}"
                    Grid.Row="1" />
            <TextBlock Text="UserName"
                       Grid.Row="2" />
            <TextBox Text="{x:Bind ViewModel.UserName, Mode=TwoWay}"
                     Grid.Row="3" />
        </Grid>
    </Grid>

**Expected behavior**
A view that successfully runs at runtime

**Your setup (please complete the following information):**
 - Visual Studio Version: 15.6.7
 - Extension Version:

**Additional context**

**Comment by mrlacey** [comment]
The [new default profiles](https://github.com/Microsoft/Rapid-XAML-Toolkit/blob/master/RapidXAML.VSIX/RapidXamlToolkit/Options/ConfiguredSettings.Default.cs) should not have this issue.

**Comment by mrlacey** [comment]
If default profiles do not cover this, please comment and I'll reopen.
