### ISSUE TITLE
Property is bound Two way even when property has only a public setter

### ISSUE THREAD

**Issue by corradocavalli** [mrlacey/Rapid-XAML-Toolkit#66]
**Describe the bug**
I have a viewmodel that exposes an int property (get only, set is private), generated view includes a slider bound in two way mode.

**To Reproduce**
Add a read only property to the viewmodel.

**Expected behavior**
Bound view not to use Two way

**Comment by Alex-Witkowski** [comment]
Same applies to a bool property with only public getter and private setter.

**Comment by mrlacey** [comment]
This is an issue with the default profiles.  X-Ref #28

**Note** Any mapping that uses a TwoWay binding and has `IfReadOnly=false` also need to include a readonly version that uses a different binding mode.

**Comment by mrlacey** [comment]
The [new default profiles](https://github.com/Microsoft/Rapid-XAML-Toolkit/blob/master/RapidXAML.VSIX/RapidXamlToolkit/Options/ConfiguredSettings.Default.cs) should not have this issue.

**Comment by mrlacey** [comment]
If default profiles do not cover this, please comment and I'll reopen.
