### ISSUE TITLE
Set DataContext in XAML dosen't make sens with UWP Profile

### ISSUE THREAD

**Issue by Alex-Witkowski** [mrlacey/Rapid-XAML-Toolkit#67]
**Describe the bug**
The UWP Profile uses x:Bind so setting DataContext in XAML doesn't work. 

**To Reproduce**
1. Go to profile selection in options
2. Set UWP or UWP (with labels) profile as active
3. Generate some XAML from VM with clipboard 
4. Paste XAML to view
5. Right click in view and select "Set DataContext"

**Expected behavior**
Option is disabled for Profiles with x:Bind or even better notification with further information is shown. 

**Your setup (please complete the following information):**
 - Visual Studio Version: 15.7.0 Preview 5
 - Extension Version: commit [63cc403]

**Additional context**
Settings DataContext in code works just fine and maybe the "Add Data Context in XAML" command should refer to add DataContext in code.

**Comment by mrlacey** [comment]
This looks like an issue with the current (temporary) profiles.
This only shows up based on profile configuration.
X-Ref #28

**Comment by mrlacey** [comment]
The [new default profiles](https://github.com/Microsoft/Rapid-XAML-Toolkit/blob/master/RapidXAML.VSIX/RapidXamlToolkit/Options/ConfiguredSettings.Default.cs) should not have this issue.

**Comment by mrlacey** [comment]
If default profiles do not cover this, please comment and I'll reopen.
