### ISSUE TITLE
Generate view misses using for ViewModel namespace

### ISSUE THREAD

**Issue by Alex-Witkowski** [mrlacey/Rapid-XAML-Toolkit#68]
**Describe the bug**
When ViewModel is in ViewModels name space and you generate the view for it the view goes to my "Views" name space which is good and in code behind the DataContext is set but the 
`using Project.ViewModels;`
is missing.

**To Reproduce**
0. Select "UWP with labels" as active profile
1. Create Folder ViewModels 
2. Add view model to folder 
3. Create view from view model
4. See code behind of view.

**Expected behavior**
As in "Demo-Basic" profile the using should be included in the generated code. 

**Your setup (please complete the following information):**
 - Visual Studio Version: 15.7.0 Preview 5
 - Extension Version: Commit [63cc403]
 - Active Profile: UWP (with labels) 

**Additional context**
Also the Name of the generated view is ugly with MainViewModelView.

**Comment by mrlacey** [comment]
This looks like an issue with the current (temporary) profiles.
X-Ref #28

**Comment by mrlacey** [comment]
The [new default profiles](https://github.com/Microsoft/Rapid-XAML-Toolkit/blob/master/RapidXAML.VSIX/RapidXamlToolkit/Options/ConfiguredSettings.Default.cs) should not have this issue.

**Comment by mrlacey** [comment]
If default profiles do not cover this, please comment and I'll reopen.
