### ISSUE TITLE
XamarinForms Profile Tweaks

### ISSUE THREAD

**Issue by LanceMcCarthy** [mrlacey/Rapid-XAML-Toolkit#76]
**Describe the bug**
There needs to be additional tweaks when generating Xamarin.Forms XAML for Enumerable properties.

**To Reproduce**
1 - Generate a View from a ViewModel that has an enumerable for any class

Observe the following
1 - x:DataType shouldn't be used (yet)
2 - ViewCell is missing, should be 1st child of DataTemplate

![image](https://user-images.githubusercontent.com/3520532/39895700-302c5258-5479-11e8-8ff6-81b7bf6b0f39.png)

I couldnt find Rapid XAML's version in the About VS, but I built it using today's commit https://github.com/Microsoft/Rapid-XAML-Toolkit/commit/a36405a196427524751208684700b9ff39d66ce7

**Comment by mrlacey** [comment]
Thanks for reporting this.
I guess you were using the "Xamarin.Forms" profile from below the dashed line in the list.
That was an old profile used in early testing. If you use "Xamarin.Forms C# StackLayout" you'll see the output you expect.

I'll remove the old profiles that should not be used.

**Comment by LanceMcCarthy** [comment]
Indeed I did use the old one. I interpreted the **Xamarin.Forms C# StackLayout** profile for generating views code using C# instead of XAML

**Comment by mrlacey** [comment]
Good point on the naming. Got any alternative suggestions?
The naming is there because it's C# and not F#.
There is no F# support but there's nothing in the UI that makes this clear.
For UWP & WPF, there is (will be) C# and VB versions.

**Comment by LanceMcCarthy** [comment]
Maybe use the language identifier after the XAML structure name? 


Here are a couple thoughts (I like the first one the best):

- Xamarin.Forms XAML StackLayout [C#] 
- Xamarin.Forms StackLayout [XAML - C#]
- Xamarin.Forms StackLayout [C# Project]

**Comment by mrlacey** [comment]
Changed name to `Xamarin.Forms StackLayout (XAML + C#)`
