### ISSUE TITLE
[XamarinForms] Autocompletion for view model properties

### ISSUE THREAD

**Issue by toomasz** [mrlacey/Rapid-XAML-Toolkit#79]
**Is your feature request related to a problem? Please describe.**

With latest update of visual studio(15.7.1) autocompletion for view model properties stopped working in DataTemplates with x:DataType specified. 
That feature request is specifically for Xamarin Forms XAML. WPF has it working.

![image](https://user-images.githubusercontent.com/3065454/40559139-0c06f0b6-6056-11e8-88a5-bad3debadfbe.png)

![image](https://user-images.githubusercontent.com/3065454/40559177-29492860-6056-11e8-8b07-cb69a5b85c7c.png)

**Describe the solution you'd like**
When typing _Property={Binding_ i would like to have list of properties of type specified by x:DataType in parent element.
That makes coding views faster and less prone to mistakes.

It would be great if XAML Toolkit restored that autocompletion.
Also i propose to make x:DataType enable autocompletion not only for data templates but for any XAML element. That would be more convenient then passing design time BindingContext with view model instance.

**Describe alternatives you've considered**
I reported a bug to Visual Studio but I doubt it will be resolved quickly:
https://developercommunity.visualstudio.com/content/problem/255781/visual-studio-1571-and-xamarin-forms-xdatatype-can.html

**Comment by mrlacey** [comment]
I'm not saying no, but I'd expect VS to be able to fix the bug that stopped this working, faster than I could reimplement an alternative intellisense provider.

**Comment by mrlacey** [comment]
It will not be possible for this project to provide an alternative to the broken Xamarin.Forms feature.

See also https://developercommunity.visualstudio.com/content/problem/249312/xamarin-xaml-intellisense-broken-since-157.html

**Comment by toomasz** [comment]
https://developercommunity.visualstudio.com/content/problem/255781/visual-studio-1571-and-xamarin-forms-xdatatype-can.html is already fixed, waiting for release that has it.

**Comment by toomasz** [comment]
https://developercommunity.visualstudio.com/content/problem/255781/visual-studio-1571-and-xamarin-forms-xdatatype-can.html is already fixed, waiting for release that has it.
