### ISSUE TITLE
VSIX - Correct license folders EULA.RTF

### ISSUE THREAD

**Issue by luizhj** [mrlacey/Rapid-XAML-Toolkit#84]
Correct the main license on source.extension.vsixmanifest from "EULA.rtf" to "License\EULA.rtf".

Correct the license folders on \language\Extension.vsixlangpack 
from "<License>..\Content\EULA.<language>.rtf</License>" 
to "<License>..\License\EULA.<language>.rtf</License>"

If the Extension Installer can't find the License it doesn't let you install the extension in a normal visual studio.

**Comment by mrlacey** [comment]
@luizhj  good catch
