### ISSUE TITLE
Error trying to import the exported file from "Xamarin.Forms C# StackLayout" profile configuration

### ISSUE THREAD

**Issue by luizhj** [mrlacey/Rapid-XAML-Toolkit#85]
**Describe the bug**
I just exported the "Xamarin.Forms C# StackLayout" profile configuration and get a error when trying to import.

**To Reproduce**
1. Go to Tools -> Options -> Rapid XAML Toolkit
2. Click on Xamarin.Forms C# StackLayout
3. Click on Export.
4. Click on Import and select the file with the exported configuration.

Error:
![image](https://user-images.githubusercontent.com/16191002/47650794-1a563200-db60-11e8-8021-0092853407b3.png)

[Xamarin.Forms C# StackLayout Custom.rxprofile.zip](https://github.com/Microsoft/Rapid-XAML-Toolkit/files/2525252/Xamarin.Forms.C.StackLayout.Custom.rxprofile.zip)

**Comment by mrlacey** [comment]
All default profiles are reporting this issue it's not just the XamForms profile.

Raising an issue with SimpelJsonAnalyzer as Array and ObservableCollection should be treated as equivalent

**Comment by mrlacey** [comment]
Good find. That issue must have existed for a very long time. 
Fixed now though
