### ISSUE TITLE
VStudio crashes when creating view with a list of a object that contains a list.

### ISSUE THREAD

**Issue by luizhj** [mrlacey/Rapid-XAML-Toolkit#89]
**Describe the bug**
VStudio crashes when creating view with a list of a object that contains a list.

**To Reproduce**
I started a simple Recipe app only for study and on a Recipe there is a list of Ingredient and a list of Instruction (step).
It is on this [repo](https://github.com/luizhj/cortanarecipes/tree/master)
Try to generate a view from MainViewModel using this part of the code:
`       private ObservableCollection<Recipe> _recipes2;`
`       public ObservableCollection<Recipe> Recipes2`
`       {`
`           get { return _recipes2; }`
`           set { SetProperty(ref _recipes2, value); }`
`       }`

Recipe class:
![image](https://user-images.githubusercontent.com/16191002/48013981-c96cad80-e10c-11e8-928d-6746071bf305.png)

MainViewModel class:
![image](https://user-images.githubusercontent.com/16191002/48014022-e3a68b80-e10c-11e8-9359-60b329582edc.png)

**Additional context**
To make a list of the Recipes in the app I created another object RecipeVM just with the id and description.

**Comment by mrlacey** [comment]
@luizhj nice find.
I have a fix and will merge it into master (hopefully) later today.

You said it was making VS crash for you but this shouldn't be the case. It should just fail silently and report the error to the output window.
Did you build a VSIX and then install it locally? Or are you using it another way?

**Comment by luizhj** [comment]
I have compiled on release mode and installed the VSIX on my main VStudio.

The VS freeze and windows show on the title bar of the software "this program stop working" and after some seconds it close the window and restart the vs.

*sorry for my bad english, i'm from Brazil :)

**Comment by mrlacey** [comment]
> I have compiled on release mode and installed the VSIX on my main VStudio.
> 
> The VS freeze and windows show on the title bar of the software "this program stop working" and after some seconds it close the window and restart the vs.

Thanks. It shouldn't crash, so I'll look at that as well.

**Comment by luizhj** [comment]
In time, i would like to thank you for your work.
I loved the time this extension is saving me on my work.

Please tell me if i can help more.

**Comment by mrlacey** [comment]
@luizhj I've just merged the code to allow the correct generation of XAML from your model. 
It just output this from your repro project.

    <StackLayout>
        <ListView ItemsSource="{Binding Recipes}">
            <ListView.ItemTemplate>
                <DataTemplate>
                    <ViewCell>
                        <StackLayout>
                            <Label Text="{Binding Id}" />
                            <Label Text="{Binding Description}" />
                            <Label Text="{Binding Note}" />
                            <Label Text="{Binding Ingredients}" />
                            <Label Text="{Binding Instructions}" />
                        </StackLayout>
                    </ViewCell>
                </DataTemplate>
            </ListView.ItemTemplate>
        </ListView>
        <Button Text="NewRecipe" Command="{Binding NewRecipe}" />
        <ActivityIndicator IsRunning="{Binding IsBusy}" />
        <Entry Keyboard="Default" Text="{Binding Title}" Placeholder="Title" />
    </StackLayout>

I've deliberately not fixed the fact that the error made a crash though. For now, I want any exception to be really obvious and crashing VS seems a powerful way to do this. I will fix this before we make a proper release and am tracking this in Issue #90 and have commented the relevant bits of code (search for `// Remove for launch. see issue #90`.)  Of course, if you don't like this you could remove those throw statements yourself ;)

> I loved the time this extension is saving me on my work.

This is good to hear. Knowing more about how you're using it, what issues you encounter, and any customizations you make can all contribute to making a better product.


> Please tell me if i can help more.

Keep raising issues for any bugs you encounter or suggestions you have for future additions/changes.

**Comment by mrlacey** [comment]
@luizhj Have you been able to confirm the above-mentioned change stops the problem you were seeing with nested generic collections?

**Comment by luizhj** [comment]
Hi @mrlacey 
I didn't have time to try again. 
I will try it out and report later.

**Comment by luizhj** [comment]
The problema was solved.
I just updated the extension and tested the same code that had crashed and this time the result view was ok.

In time, all the code was correctly indented.

![image](https://user-images.githubusercontent.com/16191002/48478945-e67c3d00-e7ec-11e8-97b5-d6b9b33bcc46.png)

**Comment by mrlacey** [comment]
> The problema was solved.
> I just updated the extension and tested the same code that had crashed and this time the result view was ok.

good to hear
