### ISSUE TITLE
Set up automated execution of tests

### ISSUE THREAD

**Issue by mrlacey** [mrlacey/Rapid-XAML-Toolkit#9]
Enable automated execution of tests on commit and PR.

**Comment by mrlacey** [comment]
Note. Can't use a free AppVeyor config while the project is private.

**Comment by crutkas** [comment]
something we need now or can set up after?  I can ask around for help on this too.

**Comment by mrlacey** [comment]
Ideally want is sooner rather than later.
Being private may be a blocker but ideally, want this by the time we start taking contributions. Tests currently run quickly but we need to make sure they're run for anything that touches the analyzers as the opportunity for regressions is large as there is some very complex stuff going on and some of the logic needs to work for both C# & VB--which is easy to overlook/forget if not actively testing both languages.

**Comment by mrlacey** [comment]
Moving to milestone1.0 as this won't be possible until after we enter public beta

**Comment by mrlacey** [comment]
This is done on appveyor for PRs and in AzurePipelines for CI & nightly builds.
